name: umi project auto build and release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: yarn env setup
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'yarn'

    - name: dependencies installing & project building
      run: |
        yarn install
        yarn build

    - name: project zipping
      uses: papeloto/action-zip@v1
      with:
        files: dist
        dest: dist.zip

    - name: zip file releasing
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        title: "Dev Dist Build"
        files: dist.zip
