name: umi project auto build and release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'umi-project'

    steps:
    - uses: actions/checkout@v3

    - name: setup nodejs and npm
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: setup yarn
      run: npm install -g yarn

    - name: setup yarn env
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'yarn'

    - run: yarn install
    - run: yarn build

    - name: project zipping
      uses: papeloto/action-zip@v1
      with:
        files: dist
        dest: dist.zip

    - name: zip file releasing
      uses: softprops/action-gh-release@v1
      # if: startsWith(github.ref, 'refs/tags/')
      with:
        tag-name: ${{ github.ref }}
        files: dist.zip


