name: umi project auto build and release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: setup yarn env
      uses: c-hive/gha-yarn-cache@v2

    - run: yarn install
    - run: yarn build

    - name: project zipping
      uses: papeloto/action-zip@v1
      with:
        files: dist
        dest: dist.zip

    - name: zip file releasing
      uses: softprops/action-gh-release@v1
      # if: startsWith(github.ref, 'refs/tags/')
      with:
        tag-name: ${{ github.ref }}
        files: dist.zip


